name = "UnicodeExponents"
uuid = "b3b1a375-d99d-4159-8659-06ebf33c5044"
authors = ["Donald Seinen"]
version = "0.0.1-DEV"

[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
